const b = {
    "id": "s5s9sbsds0s1sfsd",
    "js": "./official_view_component/official.js",
    "css": {"class": {}, "style": {}},
    "data": {
        "tag": "basic-title",
        "_gap": "",
        "attr": [],
        "elem": "div",
        "list": [],
        "inner": "",
        "_other": {},
        "_border": {},
        "_margin": {},
        "_radius": "",
        "_padding": {},
        "_reverse": "false",
        "carryData": {},
        "refer_app": "shop_template_black_style",
        "_max_width": "",
        "_background": "",
        "_style_refer": "global",
        "_hor_position": "center",
        "refer_form_data": {
            "kkw": "./?page=index",
            "size": "40",
            "color": {
                "id": "0",
                "title": "@{{theme_color.0.title}}",
                "content": "@{{theme_color.0.content}}",
                "sec-title": "@{{theme_color.0.sec-title}}",
                "background": "@{{theme_color.0.background}}",
                "sec-background": "@{{theme_color.0.sec-background}}",
                "solid-button-bg": "@{{theme_color.0.solid-button-bg}}",
                "border-button-bg": "@{{theme_color.0.border-button-bg}}",
                "solid-button-text": "@{{theme_color.0.solid-button-text}}",
                "border-button-text": "@{{theme_color.0.border-button-text}}"
            },
            "title": "熱門商品",
            "margin": {"top": "10", "left": "7", "right": "9", "bottom": "8", "toggle": true},
            "weight": "900",
            "import_": "false",
            "justify": "center",
            "padding": {"top": "20", "left": "14", "right": "18", "bottom": "16", "toggle": true},
            "size_pc": "42",
            "distance": {
                "toggle": true,
                "margin_pc": {"toggle": true},
                "padding_pc": {"toggle": true},
                "margin_phone": {"toggle": true},
                "padding_phone": {"toggle": true}
            },
            "margin_pc": {"top": "50", "left": "0", "right": "0", "bottom": "50", "toggle": false},
            "padding_pc": {"top": "0", "left": "0", "right": "0", "bottom": "0", "toggle": false},
            "size_phone": "28",
            "theme_color": {
                "id": "0",
                "title": "@{{theme_color.0.title}}",
                "content": "@{{theme_color.0.content}}",
                "background": "@{{theme_color.0.background}}",
                "solid-button-bg": "@{{theme_color.0.solid-button-bg}}",
                "border-button-bg": "@{{theme_color.0.border-button-bg}}",
                "solid-button-text": "@{{theme_color.0.solid-button-text}}",
                "border-button-text": "@{{theme_color.0.border-button-text}}"
            },
            "letter_space": "4",
            "margin_phone": {"top": "40", "left": "0", "right": "0", "bottom": "40", "toggle": false},
            "padding_phone": {"top": "-27", "left": "0", "right": "0", "bottom": "0", "toggle": false},
            "r_1716801819158": {},
            "r_1718616868830": {"type": "image", "value": ""},
            "r_1718616877262": {"type": "image", "value": ""},
            "r_1718616885960": {"type": "image", "value": ""}
        },
        "_background_setting": {"type": "none"},
        "_style_refer_global": {"index": 0}
    },
    "list": [],
    "type": "component",
    "class": "w-100",
    "index": 0,
    "label": "標題",
    "style": "",
    "global": [],
    "mobile": {
        "data": {
            "refer_app": "shop_template_black_style",
            "refer_form_data": {
                "title": "熱門商品",
                "weight": "900",
                "justify": "center",
                "size_pc": "28",
                "letter_space": "2"
            },
            "_style_refer": "global",
            "elem": "div",
            "inner": "",
            "attr": [],
            "_padding": {},
            "_margin": {},
            "_border": {},
            "_max_width": "",
            "_gap": "",
            "_background": "",
            "_other": {},
            "_radius": "",
            "_reverse": "false",
            "_hor_position": "center",
            "_background_setting": {"type": "none"},
            "_style_refer_global": {"index": 0}
        }, "refer": "custom"
    },
    "toggle": false,
    "desktop": {
        "id": "s5s9sbsds0s1sfsd",
        "js": "./official_view_component/official.js",
        "css": {"class": {}, "style": {}},
        "data": {"refer_app": "shop_template_black_style", "refer_form_data": {}},
        "list": [],
        "type": "component",
        "class": "w-100",
        "index": 0,
        "label": "標題",
        "style": "",
        "global": [],
        "toggle": false,
        "stylist": [],
        "version": "v2",
        "visible": true,
        "dataType": "static",
        "style_from": "code",
        "classDataType": "static",
        "editor_bridge": {},
        "preloadEvenet": {},
        "container_fonts": "0",
        "mobile_editable": ["title", "size_pc", "weight", "letter_space", "justify", "_container_margin"],
        "desktop_editable": [],
        "refreshAllParameter": {},
        "refreshComponentParameter": {},
        "refer": "custom"
    },
    "stylist": [],
    "version": "v2",
    "visible": true,
    "dataType": "static",
    "style_from": "code",
    "classDataType": "static",
    "editor_bridge": {},
    "preloadEvenet": {},
    "container_fonts": "0",
    "mobile_editable": ["title", "size_pc", "weight", "letter_space", "justify", "_container_margin"],
    "desktop_editable": [],
    "refreshAllParameter": {},
    "refreshComponentParameter": {},
    "formData": {}
}