export class Template_refer {
    static checkoutPage() {
        return {
            "id": "sas5s2s0s1s6s1sf",
            "js": "./official_view_component/official.js",
            "css": {
                "class": {},
                "style": {}
            },
            "data": {
                "refer_app": "shop_template_black_style",
                "tag": "sy01_checkout_detail",
                "list": [],
                "carryData": {},
                "refer_form_data": {
                    "carry_info": [{
                            "index": 0,
                            "title": "預購商品大約7~21個工作天",
                            "c_v_id": "s1s9sds9s4s2s4sa",
                            "toggle": false
                        }, {
                            "index": 1,
                            "title": "現貨商品將於下單後隔天寄出（不包含例假日）",
                            "c_v_id": "s7s9sbsas4s2s0sc",
                            "toggle": false
                        }, {
                            "index": 2,
                            "title": "如訂單量較大或是有缺貨狀況，寄出時間將不一定，敬請見諒",
                            "c_v_id": "s9sbs4sasds6s7s9",
                            "toggle": false
                        }, {
                            "index": 3,
                            "title": "寄出後大概2至3天會送達指定地點（週末不配送）",
                            "c_v_id": "s6s4s6s1s4s0s9s9",
                            "toggle": false
                        }]
                },
                "_style_refer_global": { "index": "0" },
                "_style_refer": "custom",
                "elem": "div",
                "inner": "",
                "attr": [],
                "_padding": {},
                "_margin": {},
                "_border": {},
                "_max_width": "",
                "_gap": "",
                "_background": "",
                "_other": {},
                "_radius": "",
                "_reverse": "false",
                "_hor_position": "center",
                "_background_setting": { "type": "none" }
            },
            "type": "component",
            "class": "w-100",
            "index": 0,
            "label": "一頁購物",
            "style": "",
            "bundle": {},
            "global": [],
            "toggle": false,
            "stylist": [],
            "dataType": "static",
            "style_from": "code",
            "classDataType": "static",
            "preloadEvenet": {},
            "share": {},
            "refreshAllParameter": {},
            "editor_bridge": {},
            "refreshComponentParameter": {},
            "list": [],
            "version": "v2",
            "storage": {},
            "mobile": {
                "id": "sas5s2s0s1s6s1sf",
                "js": "./official_view_component/official.js",
                "css": {
                    "class": {},
                    "style": {}
                },
                "data": { "refer_app": "shop_template_black_style" },
                "type": "component",
                "class": "w-100",
                "index": 0,
                "label": "一頁購物",
                "style": "",
                "global": [],
                "toggle": false,
                "stylist": [],
                "dataType": "static",
                "style_from": "code",
                "classDataType": "static",
                "preloadEvenet": {},
                "refreshAllParameter": {},
                "editor_bridge": {},
                "refreshComponentParameter": {},
                "list": [],
                "version": "v2",
                "mobile_editable": [],
                "desktop_editable": [],
                "refer": "custom"
            },
            "mobile_editable": [],
            "desktop": {
                "id": "sas5s2s0s1s6s1sf",
                "js": "./official_view_component/official.js",
                "css": {
                    "class": {},
                    "style": {}
                },
                "data": { "refer_app": "shop_template_black_style" },
                "type": "component",
                "class": "w-100",
                "index": 0,
                "label": "一頁購物",
                "style": "",
                "global": [],
                "toggle": false,
                "stylist": [],
                "dataType": "static",
                "style_from": "code",
                "classDataType": "static",
                "preloadEvenet": {},
                "refreshAllParameter": {},
                "editor_bridge": {},
                "refreshComponentParameter": {},
                "list": [],
                "version": "v2",
                "mobile_editable": [],
                "desktop_editable": [],
                "refer": "custom"
            },
            "desktop_editable": [],
            "container_fonts": 0
        };
    }
    static productList() {
        return {
            "id": "s1scs1s7sfses4s9",
            "js": "./official_view_component/official.js",
            "css": { "class": {}, "style": {} },
            "data": {
                "tag": "SY00-normal-products",
                "_gap": "",
                "attr": [],
                "elem": "div",
                "list": [],
                "inner": "",
                "_other": {},
                "_border": {},
                "_margin": {},
                "_radius": "",
                "_padding": { "top": "0", "left": "10", "right": "10", "bottom": "0" },
                "_reverse": "false",
                "carryData": {},
                "refer_app": "shop_template_black_style",
                "_max_width": "1200",
                "_background": "",
                "_style_refer": "custom",
                "_hor_position": "center",
                "refer_form_data": {
                    "list": [],
                    "more": "./?page=all_product",
                    "count": "50",
                    "list2": [{ "toggle": true, "product2dds": 301 }, { "toggle": true, "product2dds": 294 }],
                    "title": "本週熱門銷售排行",
                    "distance": {
                        "toggle": true,
                        "margin_pc": { "top": "0", "left": "0", "right": "0", "bottom": "0", "toggle": true },
                        "padding_pc": { "toggle": false },
                        "margin_phone": { "toggle": false },
                        "padding_phone": {}
                    },
                    "font_size": "24",
                    "font_color": "#000000",
                    "more_title": "查看更多",
                    "button_color": "#ffffff",
                    "mobile_count": "2",
                    "desktop_count": "4",
                    "product_select": { "value": [], "select": "product" },
                    "button_bg_color": "#000000",
                    "r_1714145557038": []
                },
                "_background_setting": { "type": "none" },
                "_style_refer_global": { "index": "0" }
            },
            "list": [],
            "type": "component",
            "class": "w-100",
            "index": 4,
            "label": "商品列表",
            "style": "",
            "global": [],
            "mobile": {
                "data": { "refer_app": "shop_template_black_style", "refer_form_data": { "desktop_count": "2" } },
                "refer": "custom"
            },
            "toggle": true,
            "desktop": {
                "id": "s1scs1s7sfses4s9",
                "js": "./official_view_component/official.js",
                "css": { "class": {}, "style": {} },
                "data": { "refer_app": "shop_template_black_style", "refer_form_data": {} },
                "list": [],
                "type": "component",
                "class": "w-100",
                "index": 4,
                "label": "商品列表",
                "style": "",
                "global": [],
                "toggle": true,
                "stylist": [],
                "version": "v2",
                "visible": true,
                "dataType": "static",
                "style_from": "code",
                "classDataType": "static",
                "editor_bridge": {},
                "preloadEvenet": {},
                "container_fonts": 0,
                "mobile_editable": ["desktop_count"],
                "desktop_editable": [],
                "refreshAllParameter": {},
                "refreshComponentParameter": {},
                "refer": "custom"
            },
            "stylist": [],
            "version": "v2",
            "visible": true,
            "dataType": "static",
            "style_from": "code",
            "classDataType": "static",
            "editor_bridge": {},
            "preloadEvenet": {},
            "container_fonts": 0,
            "mobile_editable": ["desktop_count"],
            "desktop_editable": [],
            "refreshAllParameter": {},
            "refreshComponentParameter": {},
            "formData": {}
        };
    }
    static bigTitle(title) {
        return {
            "id": "s4s1s2s2s9s6s7sd",
            "js": "./official_view_component/official.js",
            "css": { "class": {}, "style": {} },
            "data": {
                "refer_app": "shop_template_black_style",
                "tag": "basic-title",
                "list": [],
                "carryData": {},
                "refer_form_data": {
                    "kkw": "./?page=index",
                    "size": "40",
                    "color": {
                        "id": "0",
                        "title": "@{{theme_color.0.title}}",
                        "content": "@{{theme_color.0.content}}",
                        "background": "@{{theme_color.0.background}}",
                        "solid-button-bg": "@{{theme_color.0.solid-button-bg}}",
                        "border-button-bg": "@{{theme_color.0.border-button-bg}}",
                        "solid-button-text": "@{{theme_color.0.solid-button-text}}",
                        "border-button-text": "@{{theme_color.0.border-button-text}}"
                    },
                    "title": title,
                    "margin": { "top": "10", "left": "7", "right": "9", "bottom": "8", "toggle": true },
                    "weight": "700",
                    "import_": "false",
                    "justify": "center",
                    "padding": { "top": "20", "left": "14", "right": "18", "bottom": "16", "toggle": true },
                    "size_pc": "40",
                    "distance": {
                        "toggle": true,
                        "margin_pc": { "toggle": true },
                        "padding_pc": { "toggle": true },
                        "margin_phone": { "toggle": true },
                        "padding_phone": { "toggle": true }
                    },
                    "margin_pc": { "top": "50", "left": "0", "right": "0", "bottom": "50", "toggle": false },
                    "padding_pc": { "top": "0", "left": "0", "right": "0", "bottom": "0", "toggle": false },
                    "size_phone": "28",
                    "theme_color": {
                        "id": "0",
                        "title": "@{{theme_color.0.title}}",
                        "content": "@{{theme_color.0.content}}",
                        "background": "@{{theme_color.0.background}}",
                        "solid-button-bg": "@{{theme_color.0.solid-button-bg}}",
                        "border-button-bg": "@{{theme_color.0.border-button-bg}}",
                        "solid-button-text": "@{{theme_color.0.solid-button-text}}",
                        "border-button-text": "@{{theme_color.0.border-button-text}}"
                    },
                    "margin_phone": { "top": "40", "left": "0", "right": "0", "bottom": "40", "toggle": false },
                    "padding_phone": { "top": "-27", "left": "0", "right": "0", "bottom": "0", "toggle": false },
                    "r_1716801819158": {},
                    "r_1718616868830": { "type": "image", "value": "" },
                    "r_1718616877262": { "type": "image", "value": "" },
                    "r_1718616885960": { "type": "image", "value": "" }
                },
                "_style_refer_global": { "index": "0" },
                "_style_refer": "custom",
                "elem": "div",
                "inner": "",
                "attr": [],
                "_padding": { "top": "50", "right": "0", "bottom": "50", "left": "0" },
                "_margin": {},
                "_border": {},
                "_max_width": "",
                "_gap": "",
                "_background": "",
                "_other": {},
                "_radius": "",
                "_reverse": "false",
                "_hor_position": "center",
                "_background_setting": { "type": "none" }
            },
            "type": "component",
            "class": "w-100",
            "index": 0,
            "label": "標題",
            "style": "",
            "bundle": {},
            "global": [],
            "toggle": false,
            "stylist": [],
            "dataType": "static",
            "style_from": "code",
            "classDataType": "static",
            "preloadEvenet": {},
            "share": {},
            "formData": {},
            "refreshAllParameter": {},
            "editor_bridge": {},
            "refreshComponentParameter": {},
            "list": [],
            "version": "v2",
            "storage": {},
            "mobile": {
                "id": "s4s1s2s2s9s6s7sd",
                "js": "./official_view_component/official.js",
                "css": { "class": {}, "style": {} },
                "data": { "refer_app": "shop_template_black_style", "refer_form_data": {} },
                "type": "component",
                "class": "w-100",
                "index": 0,
                "label": "標題",
                "style": "",
                "global": [],
                "toggle": false,
                "stylist": [],
                "dataType": "static",
                "style_from": "code",
                "classDataType": "static",
                "preloadEvenet": {},
                "refreshAllParameter": {},
                "editor_bridge": {},
                "refreshComponentParameter": {},
                "list": [],
                "version": "v2",
                "mobile_editable": [],
                "desktop_editable": [],
                "container_fonts": 0,
                "refer": "custom"
            },
            "mobile_editable": [],
            "desktop": {
                "id": "s4s1s2s2s9s6s7sd",
                "js": "./official_view_component/official.js",
                "css": { "class": {}, "style": {} },
                "data": { "refer_app": "shop_template_black_style" },
                "type": "component",
                "class": "w-100",
                "index": 0,
                "label": "標題",
                "style": "",
                "global": [],
                "toggle": false,
                "stylist": [],
                "dataType": "static",
                "style_from": "code",
                "classDataType": "static",
                "preloadEvenet": {},
                "refreshAllParameter": {},
                "editor_bridge": {},
                "refreshComponentParameter": {},
                "list": [],
                "version": "v2",
                "mobile_editable": [],
                "desktop_editable": [],
                "container_fonts": 0,
                "refer": "custom"
            },
            "desktop_editable": [],
            "container_fonts": 0
        };
    }
}
